JSON_FILE_PATH = 'pets.json'
UPLOAD_FOLDER = 'static/uploads'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}
LOG_FILE_PATH = 'log.txt'
DATA_FILE = 'consultations.json'
TRAINING_DATA_FILE = 'training_data.jsonl'
API_KEY = ['AIzaSyC0CI07I0ozsLXFVNaEkMec_I4iTuyrmFE', 'AIzaSyDeFYjLrFpfwbDSepH9fXi3yg0U5u-1bVA', 'AIzaSyAcu8bfUZQB1dLZAqeKGvDOKvUAeHz0s0s']
GOOGLE_API_KEY = "your_google_api_key"
SEARCH_ENGINE_ID = "your_custom_search_engine_id"